### ISSUE TITLE
Issue with Poi 10.0.0-Beta.1

### ISSUE THREAD

**Issue by SirCheesy** [Werseter/poi-plugin-quest-browser#1]
Whenever I attempt to use quest browser since I updated Poi to 10.0.0 beta1 I just get the following text instead of the usual good stuff:

> Something went wrong with the plugin, you may report this to the plugin author or the poi dev team, with the code below.

> TypeError: Cannot read property 'unobserve' of undefined
>     at reactClass.unobserve [as componentWillUnmount] (C:\Users\CHeesy_fof`\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-browser/index.es:266:26)
>     at hh (E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:187:387)
>     at ih (E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:192:315)
>     at mi (E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:236:83)
>     at ji (E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:230:383)
>     at ki (E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:229:144)
>     at Fh (E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:226:261)
>     at bg (E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:224:86)
>     at Object.enqueueSetState (E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:140:228)
>     at Provider.F.setState (E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:13:224)
>     at E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:65:14
>     at dispatch (E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\redux\lib\redux.js:220:7)
>     at E:\Games\Kantai Collection\poi\resources\app.asar\node_modules\redux-thunk\lib\index.js:14:16
>     at action (E:\Games\Kantai Collection\poi\resources\app.asar\views\middlewares\promise-action.js:55:12)
>     at PluginManager.readPlugins (E:\Games\Kantai Collection\poi\resources\app.asar\views\services\plugin-manager\index.js:154:5)
> 
>     in reactClass
>     in Connect(reactClass)
>     in div
>     in Blueprint3.Card
>     in div
>     in StyledComponent
>     in PluginWrap
>     in NamespacesConsumerComponent
>     in WithMergedOptions
>     in WithMergedOptions(NamespacesConsumerComponent)
>     in LoadNamespace
>     in WithMergedOptions
>     in LoadNamespace(PluginWrap)
>     in div
>     in StyledComponent
>     in div
>     in StyledComponent
>     in TabContentsUnion
>     in Connect(TabContentsUnion)
>     in div
>     in StyledComponent
>     in div
>     in t
>     in div
>     in StyledComponent
>     in ControlledTabArea
>     in Connect(ControlledTabArea)
>     in NamespacesConsumerComponent
>     in WithMergedOptions
>     in WithMergedOptions(NamespacesConsumerComponent)
>     in LoadNamespace
>     in WithMergedOptions
>     in LoadNamespace(Connect(ControlledTabArea))
>     in poi-nav-tabs
>     in poi-nav
>     in div
>     in StyledComponent
>     in div
>     in StyledComponent
>     in PoiApp
>     in Connect(PoiApp)
>     in poi-main
>     in Blueprint3.ResizeSensor
>     in ThemeProvider
>     in Poi
>     in Connect(Poi)
>     in Provider
>     in I18nextProvider

**Comment by Werseter** [comment]
I have not yet used the 10.x version, so I can not guarantee the compatibility. I'll try to look into it in the evening.

**Comment by SirCheesy** [comment]
Okay. Let me know if there's anything else you need that could help.

**Comment by SirCheesy** [comment]
Seems to be fixed in the latest versions 👍
